### ISSUE TITLE
Request - Ideas for the addon

### ISSUE THREAD

**Issue by darksox** [teelolws/FishingDerbyTracker#4]
Hi, used the addon today and found it helpful. Thank you.

Could you consider adding any of these:
- Show all text in a frame (similar to quest frame) that can be movable.
- Change the font to match Quest Frame Text
- Change colors on the "how to obtain" text (blue/green, something stands out against the fish name
- Keep window open for the duration of the Fishing Derby Buff, not just while the quest is active
- Option to keep the list shown in full with maybe a tick or color change if the trophy fish has been caught
- Option to show the frame outside of the Fishing Derby (very handy as a reminder of where to find each fish)

As before, thank you. I found this very helpful and will be using it again.

**Comment by teelolws** [comment]
For your first point, you can move it in Edit Mode.

For your fifth point, thats what the addon options are for:
![image](https://github.com/user-attachments/assets/369b507b-8db0-4ba5-8975-529f6b644a9c)

**Comment by darksox** [comment]
Thank you.

**Comment by teelolws** [comment]
![image](https://github.com/user-attachments/assets/ea94ff4e-a571-4e69-b1cc-15a62888ee6d)
